@startuml
'https://plantuml.com/deployment-diagram
<style>


collections {
  BackgroundColor #Orange
  FontSize 20
}
</style>

collections "<b>Target Containers\n <b>on machine" as containers

frame "CRCCContainer Runtime Compliance Checker" as frame {
    node "\n<b>Backend App" as Backend {
      control "Checks Controller" as controller
      interface "HTTP APIs" as backendAPI
    }

    node "<b>Frontend App" as frontend {
    }
    database "\n<b>Database\n" as database
}

frontend --> backendAPI: List Containers, Apply Checks ...etc

backendAPI --> controller: trigger Checks Controller\n and read data

controller --> containers: List Containers, Apply Compliance Checks ...etc,\n through Docker API

controller --> database: Store Compliance Check Results

@enduml